/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://jjn4gpcr5rcl5hxmjzqlt7mnym.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-d5zslfbfejejvgayeunnxk75pq",
    "aws_cognito_identity_pool_id": "us-east-2:fdcf01f4-1c01-4bfc-9060-8aaf0b5e5338",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_O7v9nMQ5m",
    "aws_user_pools_web_client_id": "6rntchpkmg4u5sbv4o36t0kaa8",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": [
            "REQUIRES_NUMBERS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplofi3-storage-0158dcda55d89-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
